### ISSUE TITLE
Still requires Python 2?

### ISSUE THREAD

**Issue by dstromberg** [ugoertz/kombilo#8]
I installed kombilo on my Debian 10.7 system, using:

> apt-get install libboost-all-dev
> python3 -m pip install kombilo

And I got no errors.  However, when I try to run it, I get:

> $ kombilo 
> below cmd output started 2020 Thu Dec 31 11:04:20 AM PST
> Traceback (most recent call last):
>   File "/usr/local/bin/kombilo", line 11, in <module>
>     load_entry_point('kombilo==0.8.4', 'gui_scripts', 'kombilo')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.7/dist-packages/kombilo/kombilo.py", line 33, in <module>
>     from string import split, find, join, strip, replace
> ImportError: cannot import name 'split' from 'string' (/usr/lib/python3.7/string.py)

This suggests to me that kombilo hasn't made it past Python 2.7 yet?

Is there a branch in git that works on Python 3.x?

Thanks for the cool program!

**Comment by dstromberg** [comment]
It appears that the kombilo in github master mostly works on Python 3.7.

Apparently, it's just pypi that has a version that doesn't work on 3.x.
